# Generated by Django 6.0.3 on 2026-03-26 16:30

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        db_index=True,
                        help_text="Manufacturer batch/lot number",
                        max_length=100,
                    ),
                ),
                ("manufacture_date", models.DateField(db_index=True)),
                ("expiry_date", models.DateField(db_index=True)),
                (
                    "total_quantity",
                    models.IntegerField(
                        help_text="Total quantity in this batch (all warehouses combined)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_recalled",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this batch has been recalled",
                    ),
                ),
                (
                    "recall_reason",
                    models.TextField(
                        blank=True, help_text="Reason for recall (if recalled)"
                    ),
                ),
                ("recalled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Batch",
                "verbose_name_plural": "Batches",
                "db_table": "batches",
                "ordering": ["-manufacture_date"],
            },
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Medicine name", max_length=255
                    ),
                ),
                (
                    "generic_name",
                    models.CharField(
                        blank=True, help_text="Generic/scientific name", max_length=255
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        db_index=True, help_text="Manufacturer name", max_length=255
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        db_index=True,
                        help_text="Medicine category (e.g., Antibiotic, Analgesic)",
                        max_length=100,
                    ),
                ),
                (
                    "dosage_form",
                    models.CharField(
                        help_text="Dosage form (e.g., Tablet, Syrup, Injection)",
                        max_length=100,
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        help_text="Strength (e.g., 500mg, 10ml)", max_length=50
                    ),
                ),
                (
                    "storage_type",
                    models.CharField(
                        choices=[
                            ("refrigerated", "Refrigerated (2-8°C)"),
                            ("frozen", "Frozen (-20°C)"),
                            ("room_temp", "Room Temperature"),
                            ("controlled", "Controlled Substance"),
                        ],
                        db_index=True,
                        default="room_temp",
                        max_length=20,
                    ),
                ),
                (
                    "min_stock_threshold",
                    models.IntegerField(
                        default=10,
                        help_text="Minimum stock level before alert",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        db_index=True,
                        help_text="Stock Keeping Unit (unique identifier)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Medicine",
                "verbose_name_plural": "Medicines",
                "db_table": "medicines",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("ALLOCATION", "Initial Allocation"),
                            ("TRANSFER_OUT", "Transfer Out"),
                            ("TRANSFER_IN", "Transfer In"),
                            ("DISPATCH", "Dispatch/Sale"),
                            ("ADJUSTMENT", "Manual Adjustment"),
                            ("RECALL", "Recall Removal"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Positive for incoming, negative for outgoing"
                    ),
                ),
                (
                    "reference_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Links TRANSFER_OUT and TRANSFER_IN pairs",
                        null=True,
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Reason for movement (required for adjustments)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Movement",
                "verbose_name_plural": "Stock Movements",
                "db_table": "stock_movements",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Warehouse name",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Warehouse code (e.g., WH-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("address", models.TextField()),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("pincode", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "total_capacity",
                    models.IntegerField(
                        blank=True,
                        help_text="Total storage capacity (units)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
                "db_table": "warehouses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        help_text="Current quantity in this warehouse",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_movement_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Warehouse Stock",
                "verbose_name_plural": "Warehouse Stocks",
                "db_table": "warehouse_stock",
                "ordering": ["-updated_at"],
            },
        ),
    ]
