# Generated by Django 6.0.3 on 2026-03-26 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="recalled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recalled_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["name", "manufacturer"], name="medicines_name_016543_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["category"], name="medicines_categor_fce400_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["is_active"], name="medicines_is_acti_508f30_idx"
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="medicine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="inventory.medicine",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="inventory.batch",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_movements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "warehouse_manager"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_warehouses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="related_warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Source/destination warehouse for transfers",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_movements",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="warehousestock",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouse_stocks",
                to="inventory.batch",
            ),
        ),
        migrations.AddField(
            model_name="warehousestock",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouse_stocks",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["batch_number"], name="batches_batch_n_62e6fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["expiry_date"], name="batches_expiry__d11ac0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["is_recalled"], name="batches_is_reca_9d468e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["medicine", "expiry_date"], name="batches_medicin_4a1314_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_quantity__gte", 0)),
                name="batch_total_quantity_non_negative",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="batch",
            unique_together={("medicine", "batch_number")},
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["code"], name="warehouses_code_339055_idx"),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["is_active"], name="warehouses_is_acti_178fdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["city"], name="warehouses_city_c01192_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["batch", "warehouse"], name="stock_movem_batch_i_e997ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_type"], name="stock_movem_movemen_d922c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["performed_at"], name="stock_movem_perform_6fa10b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["performed_by"], name="stock_movem_perform_e193c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["reference_id"], name="stock_movem_referen_f2f2a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehousestock",
            index=models.Index(
                fields=["warehouse", "batch"], name="warehouse_s_warehou_7af120_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehousestock",
            index=models.Index(
                fields=["quantity"], name="warehouse_s_quantit_67489e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehousestock",
            index=models.Index(
                fields=["updated_at"], name="warehouse_s_updated_4b6817_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="warehousestock",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)),
                name="warehouse_stock_quantity_non_negative",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="warehousestock",
            unique_together={("warehouse", "batch")},
        ),
    ]
