# Generated by Django 6.0.3 on 2026-03-26 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecallRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Detailed reason for recall request"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low - Quality Issue"),
                            ("MEDIUM", "Medium - Minor Safety"),
                            ("HIGH", "High - Major Safety"),
                            ("CRITICAL", "Critical - Life Threatening"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        help_text="Severity level of the recall",
                        max_length=10,
                    ),
                ),
                (
                    "affected_quantity",
                    models.IntegerField(
                        blank=True,
                        help_text="Total quantity affected by recall",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_notes",
                    models.TextField(blank=True, help_text="Admin notes during review"),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection (if rejected)"
                    ),
                ),
                (
                    "regulatory_reference",
                    models.CharField(
                        blank=True,
                        help_text="Regulatory body reference number (if applicable)",
                        max_length=255,
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True,
                        help_text="External reference (manufacturer notice, etc.)",
                        max_length=255,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "affected_warehouses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Warehouses with affected stock",
                        related_name="recall_requests",
                        to="inventory.warehouse",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recall_requests",
                        to="inventory.batch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recall Request",
                "verbose_name_plural": "Recall Requests",
                "db_table": "recall_requests",
                "ordering": ["-requested_at"],
            },
        ),
    ]
