# Generated by Django 6.0.3 on 2026-03-26 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recalls", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recallrequest",
            name="requested_by",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["admin", "warehouse_manager"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_recalls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recallrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "admin"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_recalls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="recallrequest",
            index=models.Index(fields=["status"], name="recall_requ_status_790d10_idx"),
        ),
        migrations.AddIndex(
            model_name="recallrequest",
            index=models.Index(
                fields=["severity"], name="recall_requ_severit_c66ef6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recallrequest",
            index=models.Index(
                fields=["requested_at"], name="recall_requ_request_d57265_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recallrequest",
            index=models.Index(
                fields=["batch", "status"], name="recall_requ_batch_i_d21520_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recallrequest",
            index=models.Index(
                fields=["requested_by"], name="recall_requ_request_fc8822_idx"
            ),
        ),
    ]
