# Generated by Django 6.0.3 on 2026-05-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recalls", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recallrequest",
            name="external_reference",
            field=models.CharField(
                blank=True,
                help_text="External manufacturer notice reference",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="recallrequest",
            name="regulatory_reference",
            field=models.CharField(
                blank=True, help_text="Regulatory body reference number", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="recallrequest",
            name="rejection_reason",
            field=models.TextField(blank=True, help_text="Reason for rejection"),
        ),
    ]
